import 'dart:typed_data';
import 'dart:io';

import 'package:intl/intl.dart';
import 'package:my_first_app/features/ai_generation/models/generated_output_model.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';

class PdfExportService {
  Future<Uint8List> buildGeneratedOutputPdf(GeneratedOutputModel output) async {
    final document = pw.Document(
      title: output.title,
      author: 'AI App Builder',
      creator: 'AI App Builder',
      subject: formatOutputType(output.outputType),
    );

    final generatedDate = DateFormat('yyyy-MM-dd').format(output.createdAt);
    final content = output.content.trim().isEmpty
        ? 'No generated content is available for this output.'
        : output.content.trim();

    document.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(40, 42, 40, 44),
        header: (context) => _buildHeader(output, generatedDate),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          pw.SizedBox(height: 18),
          ..._buildMarkdownLikeContent(content),
        ],
      ),
    );

    return document.save();
  }

  Future<File> savePdfToDevice({
    required GeneratedOutputModel output,
    required Uint8List bytes,
  }) async {
    final directory = await getApplicationDocumentsDirectory();
    final fileName = buildFileName(output);
    final file = File('${directory.path}/$fileName');
    return file.writeAsBytes(bytes, flush: true);
  }

  Future<void> sharePdf({
    required GeneratedOutputModel output,
    required Uint8List bytes,
  }) async {
    final fileName = buildFileName(output);
    await SharePlus.instance.share(
      ShareParams(
        files: [
          XFile.fromData(bytes, name: fileName, mimeType: 'application/pdf'),
        ],
        subject: output.title,
        text: 'Generated by AI App Builder',
      ),
    );
  }

  Future<void> previewPdf({
    required GeneratedOutputModel output,
    required Uint8List bytes,
  }) async {
    await Printing.layoutPdf(
      name: buildFileName(output),
      onLayout: (_) async => bytes,
    );
  }

  String buildFileName(GeneratedOutputModel output) {
    final projectPart = sanitizeFileName(output.projectTitle ?? output.title);
    final typePart = sanitizeFileName(formatOutputType(output.outputType));
    final datePart = DateFormat('yyyy-MM-dd').format(output.createdAt);
    final base = '${projectPart}_${typePart}_$datePart';
    final trimmed = base.length > 90 ? base.substring(0, 90) : base;
    return '$trimmed.pdf';
  }

  String sanitizeFileName(String value) {
    final cleaned = value
        .toLowerCase()
        .replaceAll(RegExp(r'[^a-z0-9\s_-]'), '')
        .trim()
        .replaceAll(RegExp(r'[\s_]+'), '-')
        .replaceAll(RegExp(r'-+'), '-');
    return cleaned.isEmpty ? 'generated-output' : cleaned;
  }

  String formatOutputType(String value) {
    return value.replaceAll('_', ' ').replaceAll('-', ' ').trim().isEmpty
        ? 'generated output'
        : value.replaceAll('_', ' ').replaceAll('-', ' ');
  }

  pw.Widget _buildHeader(GeneratedOutputModel output, String generatedDate) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 14),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(color: PdfColors.blueGrey200, width: 1),
        ),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'AI App Builder',
            style: pw.TextStyle(
              fontSize: 18,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.indigo700,
            ),
          ),
          pw.SizedBox(height: 6),
          pw.Text(
            output.projectTitle ?? output.title,
            style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 3),
          pw.Text(
            '${formatOutputType(output.outputType)} • $generatedDate',
            style: const pw.TextStyle(
              fontSize: 10,
              color: PdfColors.blueGrey600,
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 10),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          top: pw.BorderSide(color: PdfColors.blueGrey200, width: 1),
        ),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated by AI App Builder',
            style: const pw.TextStyle(
              fontSize: 9,
              color: PdfColors.blueGrey600,
            ),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: const pw.TextStyle(
              fontSize: 9,
              color: PdfColors.blueGrey600,
            ),
          ),
        ],
      ),
    );
  }

  List<pw.Widget> _buildMarkdownLikeContent(String content) {
    final widgets = <pw.Widget>[];
    final codeBuffer = StringBuffer();
    var inCodeBlock = false;

    for (final rawLine in content.split('\n')) {
      final line = rawLine.trimRight();

      if (line.trim().startsWith('```')) {
        if (inCodeBlock) {
          widgets.add(_codeBlock(codeBuffer.toString().trimRight()));
          codeBuffer.clear();
          inCodeBlock = false;
        } else {
          inCodeBlock = true;
        }
        continue;
      }

      if (inCodeBlock) {
        codeBuffer.writeln(line);
        continue;
      }

      if (line.trim().isEmpty) {
        widgets.add(pw.SizedBox(height: 8));
        continue;
      }

      final trimmed = line.trim();
      if (trimmed.startsWith('#')) {
        final level = trimmed.indexOf(' ') <= 0
            ? 1
            : trimmed.split(' ').first.length;
        final text = trimmed.replaceFirst(RegExp(r'^#+\s*'), '');
        widgets.add(_heading(text, level));
      } else if (RegExp(r'^[-*]\s+').hasMatch(trimmed)) {
        widgets.add(_bullet(trimmed.replaceFirst(RegExp(r'^[-*]\s+'), '')));
      } else if (RegExp(r'^\d+[.)]\s+').hasMatch(trimmed)) {
        widgets.add(_numbered(trimmed));
      } else {
        widgets.add(_paragraph(trimmed));
      }
    }

    if (codeBuffer.isNotEmpty) {
      widgets.add(_codeBlock(codeBuffer.toString().trimRight()));
    }

    return widgets;
  }

  pw.Widget _heading(String text, int level) {
    final size = level <= 1
        ? 20.0
        : level == 2
        ? 16.0
        : 13.0;
    return pw.Padding(
      padding: const pw.EdgeInsets.only(top: 14, bottom: 7),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: size,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.indigo800,
        ),
      ),
    );
  }

  pw.Widget _paragraph(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 6),
      child: pw.Text(
        text,
        style: const pw.TextStyle(fontSize: 11, height: 1.35),
      ),
    );
  }

  pw.Widget _bullet(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(left: 10, bottom: 5),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('• ', style: const pw.TextStyle(fontSize: 11)),
          pw.Expanded(child: _paragraph(text)),
        ],
      ),
    );
  }

  pw.Widget _numbered(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(left: 6, bottom: 5),
      child: pw.Text(
        text,
        style: const pw.TextStyle(fontSize: 11, height: 1.35),
      ),
    );
  }

  pw.Widget _codeBlock(String code) {
    return pw.Container(
      width: double.infinity,
      margin: const pw.EdgeInsets.symmetric(vertical: 8),
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(6),
        border: pw.Border.all(color: PdfColors.grey300),
      ),
      child: pw.Text(
        code.isEmpty ? ' ' : code,
        style: pw.TextStyle(font: pw.Font.courier(), fontSize: 9, height: 1.25),
      ),
    );
  }
}
