import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";
const corsHeaders = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type", "Access-Control-Allow-Methods": "POST, OPTIONS" };
function jsonResponse(body: unknown, status = 200) { return new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } }); }
function env(name: string) { const v = Deno.env.get(name); if (!v) throw new Error(`Missing env: ${name}`); return v; }
async function context(req: Request) { const url=env("SUPABASE_URL"), anon=env("SUPABASE_ANON_KEY"), service=env("SUPABASE_SERVICE_ROLE_KEY"); const authorization=req.headers.get("Authorization"); if(!authorization) throw new Response(JSON.stringify({error:"Missing authorization."}),{status:401,headers:{...corsHeaders,"Content-Type":"application/json"}}); const userClient=createClient(url,anon,{global:{headers:{Authorization:authorization}}}); const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}}); const {data:{user},error}=await userClient.auth.getUser(); if(error||!user) throw new Response(JSON.stringify({error:"Invalid session."}),{status:401,headers:{...corsHeaders,"Content-Type":"application/json"}}); return {admin,user}; }
async function isAdmin(admin:any,userId:string){ const {data}=await admin.from("profiles").select("role").eq("id",userId).maybeSingle(); return data?.role === "admin"; }
async function hasPremium(admin:any,userId:string){ const {data}=await admin.from("profiles").select("role,subscription_tier").eq("id",userId).maybeSingle(); return data?.role === "admin" || data?.role === "premium_user" || data?.subscription_tier === "premium"; }
async function audit(admin:any,actor:string,action:string,metadata:Record<string,unknown>){ await admin.from("audit_logs").insert({actor_user_id:actor, action, metadata}).throwOnError?.(); }

serve(async (req)=>{ if(req.method==="OPTIONS") return new Response("ok",{headers:corsHeaders}); try{ const {admin,user}=await context(req); if(!(await isAdmin(admin,user.id))) return jsonResponse({error:"Admin access required."},403); const {reviewId,status}=await req.json(); if(!["pending","published","hidden"].includes(status)) return jsonResponse({error:"Invalid status."},400); const {data:review,error}=await admin.from("marketplace_template_reviews").update({status}).eq("id",reviewId).select().single(); if(error) throw error; await admin.rpc("recalculate_marketplace_template_rating",{p_template_id:review.template_id}); await audit(admin,user.id,"moderate_template_review",{reviewId,status}); return jsonResponse({success:true,review}); } catch(e){ if(e instanceof Response) return e; return jsonResponse({error:e instanceof Error?e.message:"Unknown error."},500); } });
