import { createSupabaseServerClientOrNull } from '@/lib/supabase/server';
import { getCurrentUserAndProfile } from '@/lib/dashboard/queries';
import type { AdminAuditLog, AdminMessage, AdminOutput, AdminOverview, AdminProfile, AdminProject, AdminReview, AdminTeam, AdminTemplate } from './types';

export async function requireAdmin(){const current=await getCurrentUserAndProfile(); return {...current,isAdmin:current.profile?.role==='admin'};}
async function safe<T>(fn:()=>Promise<T>, fallback:T):Promise<T>{try{return await fn();}catch{return fallback;}}
async function count(table:string){const supabase=await createSupabaseServerClientOrNull(); if(!supabase) return 0; const {count}=await supabase.from(table).select('*',{count:'exact',head:true}); return count??0;}
export async function getAdminOverview():Promise<AdminOverview>{const [totalUsers,totalProjects,totalOutputs,totalTemplates,totalTeams,feedbackMessages,waitlistSubscribers,recentAuditLogs,recentUsers]=await Promise.all([count('profiles'),count('app_projects'),count('generated_outputs'),count('marketplace_templates'),count('teams'),count('contact_messages'),count('waitlist_subscribers'),getAdminAuditLogs(5),getAdminUsers('', 'all', 'all', 5)]); const premiumUsers=recentUsers.filter(u=>u.subscription_tier==='premium'||u.role==='premium_user').length; return {totalUsers,premiumUsers,freeUsers:Math.max(totalUsers-premiumUsers,0),totalProjects,totalOutputs,totalTemplates,totalTeams,feedbackMessages,waitlistSubscribers,recentAuditLogs,recentUsers};}
export async function getAdminUsers(search='',role='all',plan='all',limit=100):Promise<AdminProfile[]>{return safe(async()=>{const supabase=await createSupabaseServerClientOrNull(); if(!supabase) return []; let q=supabase.from('profiles').select('id,email,full_name,role,subscription_tier,created_at,disabled').order('created_at',{ascending:false}).limit(limit); if(role!=='all') q=q.eq('role',role); if(plan!=='all') q=q.eq('subscription_tier',plan); if(search) q=q.or(`email.ilike.%${search}%,full_name.ilike.%${search}%`); const {data}=await q; return (data??[]) as AdminProfile[];},[]);}
export async function getAdminUserDetail(id:string){return safe(async()=>{const supabase=await createSupabaseServerClientOrNull(); if(!supabase) return null; const [profile,projects,outputs,usage,teams,audit]=await Promise.all([supabase.from('profiles').select('*').eq('id',id).maybeSingle(),supabase.from('app_projects').select('*').or(`owner_user_id.eq.${id},user_id.eq.${id},created_by_user_id.eq.${id}`).limit(25),supabase.from('generated_outputs').select('*').eq('user_id',id).limit(25),supabase.from('usage_limits').select('*').eq('user_id',id).maybeSingle(),supabase.from('team_members').select('*,teams(id,name)').eq('user_id',id).limit(25),supabase.from('audit_logs').select('*').or(`actor_user_id.eq.${id},target_user_id.eq.${id}`).limit(25)]); return {profile:profile.data,projects:projects.data??[],outputs:outputs.data??[],usage:usage.data,teams:teams.data??[],audit:audit.data??[]};},null);}
export async function getAdminProjects():Promise<AdminProject[]>{return safe(async()=>{const supabase=await createSupabaseServerClientOrNull(); if(!supabase) return []; const {data}=await supabase.from('app_projects').select('*').order('created_at',{ascending:false}).limit(200); return (data??[]) as AdminProject[];},[]);}
export async function getAdminOutputs():Promise<AdminOutput[]>{return safe(async()=>{const supabase=await createSupabaseServerClientOrNull(); if(!supabase) return []; const {data}=await supabase.from('generated_outputs').select('*').order('created_at',{ascending:false}).limit(200); return (data??[]) as AdminOutput[];},[]);}
export async function getAdminTemplates():Promise<AdminTemplate[]>{return safe(async()=>{const supabase=await createSupabaseServerClientOrNull(); if(!supabase) return []; const {data}=await supabase.from('marketplace_templates').select('*').order('created_at',{ascending:false}).limit(200); return (data??[]) as AdminTemplate[];},[]);}
export async function getAdminReviews():Promise<AdminReview[]>{return safe(async()=>{const supabase=await createSupabaseServerClientOrNull(); if(!supabase) return []; const {data}=await supabase.from('marketplace_template_reviews').select('*').order('created_at',{ascending:false}).limit(200); return (data??[]) as AdminReview[];},[]);}
export async function getAdminTeams():Promise<AdminTeam[]>{return safe(async()=>{const supabase=await createSupabaseServerClientOrNull(); if(!supabase) return []; const {data}=await supabase.from('teams').select('*').order('created_at',{ascending:false}).limit(200); return (data??[]) as AdminTeam[];},[]);}
export async function getAdminFeedback():Promise<AdminMessage[]>{return safe(async()=>{const supabase=await createSupabaseServerClientOrNull(); if(!supabase) return []; const {data}=await supabase.from('contact_messages').select('*').order('created_at',{ascending:false}).limit(200); return (data??[]) as AdminMessage[];},[]);}
export async function getAdminWaitlist():Promise<AdminMessage[]>{return safe(async()=>{const supabase=await createSupabaseServerClientOrNull(); if(!supabase) return []; const {data}=await supabase.from('waitlist_subscribers').select('*').order('created_at',{ascending:false}).limit(500); return (data??[]) as AdminMessage[];},[]);}
export async function getAdminAuditLogs(limit=200):Promise<AdminAuditLog[]>{return safe(async()=>{const supabase=await createSupabaseServerClientOrNull(); if(!supabase) return []; const {data}=await supabase.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(limit); return (data??[]) as AdminAuditLog[];},[]);}
export async function getAdminAnalytics(){return safe(async()=>{const supabase=await createSupabaseServerClientOrNull(); if(!supabase) return {summary:null,daily:[],templates:[],subs:[]}; const [summary,daily,templates,subs]=await Promise.all([supabase.rpc('admin_platform_summary'),supabase.rpc('admin_daily_usage'),supabase.rpc('admin_template_usage'),supabase.rpc('admin_subscription_summary')]); return {summary:summary.data,daily:daily.data??[],templates:templates.data??[],subs:subs.data??[]};},{summary:null,daily:[],templates:[],subs:[]});}
