'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import Button from '@/components/ui/Button';
import Input from '@/components/ui/Input';
import { createSupabaseBrowserClient, isSupabaseBrowserConfigured } from '@/lib/supabase/browser';
import { getSupabaseConfigError } from '@/lib/supabase/config';
export default function SignupForm(){ const [form,setForm]=useState({fullName:'',email:'',password:'',confirm:''}); const [message,setMessage]=useState<string|null>(null); const [loading,setLoading]=useState(false); function set(k:string,v:string){setForm(f=>({...f,[k]:v}));} async function submit(e:FormEvent){e.preventDefault(); setMessage(null); if(!form.fullName.trim()||!/^\S+@\S+\.\S+$/.test(form.email)||form.password.length<6||form.password!==form.confirm){setMessage('Enter name, valid email, matching password of at least 6 characters.');return;} if(!isSupabaseBrowserConfigured()){setMessage(getSupabaseConfigError()); return;} setLoading(true); const {error}=await createSupabaseBrowserClient().auth.signUp({email:form.email,password:form.password,options:{data:{full_name:form.fullName},emailRedirectTo:`${location.origin}/dashboard`}}); setLoading(false); setMessage(error?error.message:'Account created. Check your email if confirmation is enabled, then log in.');}
return <form onSubmit={submit} className="card mx-auto max-w-md space-y-4"><h1 className="text-3xl font-black">Sign up</h1><Input placeholder="Full name" value={form.fullName} onChange={(e)=>set('fullName',e.target.value)}/><Input type="email" placeholder="Email" value={form.email} onChange={(e)=>set('email',e.target.value)}/><Input type="password" placeholder="Password" value={form.password} onChange={(e)=>set('password',e.target.value)}/><Input type="password" placeholder="Confirm password" value={form.confirm} onChange={(e)=>set('confirm',e.target.value)}/><Button className="w-full" disabled={loading}>{loading?'Creating...':'Create account'}</Button>{message&&<p className="text-sm text-amber-200">{message}</p>}<p className="text-sm text-slate-400">Already have an account? <Link href="/login">Log in</Link></p></form>;}
