import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";
const corsHeaders = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type", "Access-Control-Allow-Methods": "POST, OPTIONS" };
function jsonResponse(body: unknown, status = 200) { return new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } }); }
function env(name: string) { const v = Deno.env.get(name); if (!v) throw new Error(`Missing env: ${name}`); return v; }
async function context(req: Request) { const url=env("SUPABASE_URL"), anon=env("SUPABASE_ANON_KEY"), service=env("SUPABASE_SERVICE_ROLE_KEY"); const authorization=req.headers.get("Authorization"); if(!authorization) throw new Response(JSON.stringify({error:"Missing authorization."}),{status:401,headers:{...corsHeaders,"Content-Type":"application/json"}}); const userClient=createClient(url,anon,{global:{headers:{Authorization:authorization}}}); const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}}); const {data:{user},error}=await userClient.auth.getUser(); if(error||!user) throw new Response(JSON.stringify({error:"Invalid session."}),{status:401,headers:{...corsHeaders,"Content-Type":"application/json"}}); return {admin,user}; }
async function isAdmin(admin:any,userId:string){ const {data}=await admin.from("profiles").select("role").eq("id",userId).maybeSingle(); return data?.role === "admin"; }
async function hasPremium(admin:any,userId:string){ const {data}=await admin.from("profiles").select("role,subscription_tier").eq("id",userId).maybeSingle(); return data?.role === "admin" || data?.role === "premium_user" || data?.subscription_tier === "premium"; }
async function audit(admin:any,actor:string,action:string,metadata:Record<string,unknown>){ await admin.from("audit_logs").insert({actor_user_id:actor, action, metadata}).throwOnError?.(); }

serve(async (req)=>{ if(req.method==="OPTIONS") return new Response("ok",{headers:corsHeaders}); try{ const {admin,user}=await context(req); const {templateId,projectTitle}=await req.json(); if(!templateId) return jsonResponse({error:"templateId is required."},400); const {data:t,error}=await admin.from("marketplace_templates").select().eq("id",templateId).maybeSingle(); if(error) throw error; if(!t || t.status!=="published") return jsonResponse({error:"Template not found."},404); if(t.access_type==="premium" && !(await hasPremium(admin,user.id))) return jsonResponse({error:"premium_required"},402); if(t.access_type==="admin_only" && !(await isAdmin(admin,user.id))) return jsonResponse({error:"admin_only"},403); const payload=t.template_payload ?? {}; const features=Array.isArray(t.features)?t.features:[]; const {data:project,error:projectError}=await admin.from("app_projects").insert({name: projectTitle || t.title, description: t.short_description, owner_user_id:user.id, created_by_user_id:user.id, user_id:user.id, visibility:"private", template_id:t.id, target_platform: payload.target_platform || t.target_platform, selected_stack: payload.selected_stack || t.recommended_stack, main_features: payload.main_features || features, status:"planning"}).select().single(); if(projectError) throw projectError; await admin.from("marketplace_template_usage").insert({user_id:user.id, template_id:t.id, project_id:project.id, action_type:"used"}); await admin.from("analytics_events").insert({user_id:user.id,event_name:"marketplace_template_used",event_category:"project",entity_type:"project",entity_id:project.id,metadata:{templateId:t.id},platform:"server"}); return jsonResponse({success:true,project}); } catch(e){ if(e instanceof Response) return e; return jsonResponse({error:e instanceof Error?e.message:"Unknown error."},500); } });
