import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...corsHeaders,"Content-Type":"application/json"}});
function env(n:string){const v=Deno.env.get(n); if(!v) throw new Error(`Missing ${n}`); return v;}
async function ctx(req:Request){const auth=req.headers.get('Authorization'); if(!auth) throw json({error:'Missing authorization'},401); const admin=createClient(env('SUPABASE_URL'),env('SUPABASE_SERVICE_ROLE_KEY'),{auth:{persistSession:false}}); const userClient=createClient(env('SUPABASE_URL'),env('SUPABASE_ANON_KEY'),{global:{headers:{Authorization:auth}}}); const {data:{user}}=await userClient.auth.getUser(); if(!user) throw json({error:'Invalid session'},401); const {data:p}=await admin.from('profiles').select('role').eq('id',user.id).maybeSingle(); if(p?.role!=='admin') throw json({error:'Admin required'},403); return {admin,user};}
async function audit(admin:any,actor:string,action:string,metadata:Record<string,unknown>){await admin.from('audit_logs').insert({actor_user_id:actor,action,metadata});}

serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});try{const {admin,user}=await ctx(req);const {userId,role}=await req.json(); if(!['user','premium_user','admin'].includes(role)) return json({error:'Invalid role'},400); const {data,error}=await admin.from('profiles').update({role}).eq('id',userId).select().single(); if(error) throw error; await audit(admin,user.id,'admin_update_user_role',{userId,role}); return json({success:true,profile:data});}catch(e){if(e instanceof Response)return e;return json({error:e instanceof Error?e.message:'Unknown error'},500)}});
